name: teste-php

services:
  app:
    container_name: app
    build:
      context: .
      args:
        COMPOSER_VERSION: ${COMPOSER_VERSION:?COMPOSER_VERSION não definido no .env}
        XDEBUG_VERSION: ${XDEBUG_VERSION:?XDEBUG_VERSION não definido no .env}
        NODE_VERSION: ${NODE_VERSION:?NODE_VERSION não definido no .env}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG:?INSTALL_XDEBUG não definido no .env}
        UID: ${UID:?UID não definido no .env}
        GID: ${GID:?GID não definido no .env}
        TZ: ${TZ:-UTC}
    environment:
      APP_NAME: "Avaliacao EAD"
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB:?POSTGRES_DB não definido no .env}
      DB_USERNAME: ${POSTGRES_USER:?POSTGRES_USER não definido no .env}
      DB_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD não definido no .env}

      CACHE_STORE: redis
      QUEUE_CONNECTION: sync

      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: ${REDIS_PORT:-6379}:6379
    volumes:
      - ./app:/var/www/html
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  postgres:
    container_name: db
    image: postgres:17-alpine3.23
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB não definido no .env}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER não definido no .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD não definido no .env}
      TZ: ${TZ:-UTC}
    command: >
      postgres
      -c timezone=${TZ:-UTC}
      -c log_timezone=${TZ:-UTC}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:?POSTGRES_USER não definido no .env} -d ${POSTGRES_DB:?POSTGRES_DB não definido no .env}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - app_network
  
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge