FROM php:8.4.2-fpm-alpine3.21

ARG COMPOSER_VERSION=2.9.7
ARG XDEBUG_VERSION=3.5.1
ARG NODE_VERSION=25.9.0

ARG INSTALL_XDEBUG=false
ARG UID=1000
ARG GID=1000

ARG TZ='America/Sao_Paulo'

ENV COMPOSER_VERSION=${COMPOSER_VERSION} \
  XDEBUG_VERSION=${XDEBUG_VERSION} \
  NODE_VERSION=${NODE_VERSION} \
  INSTALL_XDEBUG=${INSTALL_XDEBUG} \
  TZ=${TZ}